### ISSUE TITLE
Unlock sidebar

### ISSUE THREAD

**Issue by trag1c** [Gwion/Gwion#260] opened 2024-05-08 10:00 UTC
The sidebar seems to be locked (even though I believe mdBook allows toggling it?) which makes docs hard to read when using a narrow window

<img width="1251" alt="3567" src="https://github.com/Gwion/Gwion/assets/77130613/88787f70-fcb1-491d-bdf3-6b2b810d545c">

**Comment by fennecdjay** [comment] 2024-05-08 15:48
thanks for reporting!
i had not checked the docs in a while, but i can reproduce (this previously was working).
i'll be checking that asap.
meanwhile, if you have any ideas on how to fix, i'd be glad to hear them.

have a nice day

**Comment by fennecdjay** [comment] 2024-05-09 11:45
i updated mdbook and it looks like it's working now.
(i ditched the playground thing for now but OTOH the gwion org has no way to host the backend atm).

@trag1c can you confirm it works on your side?
if so i'll close the issue.

**Comment by trag1c** [comment] 2024-05-09 11:47
Yup, works great now!

**Comment by fennecdjay** [comment] 2024-05-09 11:50
thank you so much.
closing as fixed

**Closed by fennecdjay** 2024-05-09 11:50 UTC
